## Тема “Вычисления с помощью Numpy”

### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [42]:
import numpy as np

In [43]:
a1 = np.array([1, 2, 3, 3, 1])
a2 = np.array([6, 8, 11, 10, 7])
a = np.vstack([a1, a2])
a = a.reshape(5, 2)
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [44]:
mean_a = np.mean(a, axis = 0)
mean_a

array([4.6, 5.8])

### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [45]:
a_centered = a - mean_a
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])

### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [46]:
a_centered_sp = a_centered.T.dot(a_centered)
a_centered_sp

array([[69.2, 41.6],
       [41.6, 50.8]])

In [47]:
N = a.shape[0]
N

5

In [48]:
a_centered_sp / (N - 1)

array([[17.3, 10.4],
       [10.4, 12.7]])

### Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [49]:
np.cov(a.T)

array([[17.3, 10.4],
       [10.4, 12.7]])

## Тема “Работа с данными в Pandas”

### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [50]:
import pandas as pd

In [51]:
data = {'author_id' : [1, 2, 3], 'author_name' : ['Turgenev', 'Chechov', 'Ostrovsky']}
data

{'author_id': [1, 2, 3], 'author_name': ['Turgenev', 'Chechov', 'Ostrovsky']}

In [52]:
authors = pd.DataFrame(data)
authors

author_id author_name
0          1    Turgenev
1          2     Chechov
2          3   Ostrovsky

In [53]:
data = {'author_id':[1, 1, 1, 2, 2, 3, 3],
        'book_title':['Fathers and Sons', 'Rudin', "Noble's Nest", 'Fat and Thin', 'Lady with a Dog', 'Thunderstorm', 'Talents and Fans'],
        'price':[450, 300, 350, 500, 450, 370, 290]}
data

{'author_id': [1, 1, 1, 2, 2, 3, 3],
 'book_title': ['Fathers and Sons',
  'Rudin',
  "Noble's Nest",
  'Fat and Thin',
  'Lady with a Dog',
  'Thunderstorm',
  'Talents and Fans'],
 'price': [450, 300, 350, 500, 450, 370, 290]}

In [54]:
book = pd.DataFrame(data)
book

author_id        book_title  price
0          1  Fathers and Sons    450
1          1             Rudin    300
2          1      Noble's Nest    350
3          2      Fat and Thin    500
4          2   Lady with a Dog    450
5          3      Thunderstorm    370
6          3  Talents and Fans    290

### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [55]:
authors_price = book.merge(authors, how = 'left', on = 'author_id')
authors_price

author_id        book_title  price author_name
0          1  Fathers and Sons    450    Turgenev
1          1             Rudin    300    Turgenev
2          1      Noble's Nest    350    Turgenev
3          2      Fat and Thin    500     Chechov
4          2   Lady with a Dog    450     Chechov
5          3      Thunderstorm    370   Ostrovsky
6          3  Talents and Fans    290   Ostrovsky

### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [56]:
top5 = authors_price.sort_values(by = 'price', axis = 0, ascending = False).head(5)
top5

author_id        book_title  price author_name
3          2      Fat and Thin    500     Chechov
0          1  Fathers and Sons    450    Turgenev
4          2   Lady with a Dog    450     Chechov
5          3      Thunderstorm    370   Ostrovsky
2          1      Noble's Nest    350    Turgenev

### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.

In [57]:
authors_stat = pd.DataFrame()
#authors_stat['author_name'] = authors_price.author_name.unique()
authors_stat[['min_price', 'max_price', 'mean_price']] =\
authors_price.groupby(by = 'author_name')['price'].agg(['min', 'max', 'mean'])
authors_stat.reset_index(inplace = True)
authors_stat

author_name  min_price  max_price  mean_price
0     Chechov        450        500  475.000000
1   Ostrovsky        290        370  330.000000
2    Turgenev        300        450  366.666667

### Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [58]:
authors_price['cover'] = ['hard', 'soft', 'soft', 'hard', 'hard', 'soft', 'soft']

In [59]:
?pd.pivot_table

In [60]:
book_info = pd.pivot_table(
    authors_price,
    values='price',
    index='author_name',
    columns='cover',
    aggfunc='sum',
    fill_value=0,
    margins=True,
    dropna=True,
    margins_name='All',
)
book_info

cover        hard  soft   All
author_name                  
Chechov       950     0   950
Ostrovsky       0   660   660
Turgenev      450   650  1100
All          1400  1310  2710

In [61]:
book_info.to_pickle('book_info.pkl')

In [62]:
book_info2 = pd.read_pickle('book_info.pkl')

In [63]:
print(book_info2 == book_info)

cover        hard  soft   All
author_name                  
Chechov      True  True  True
Ostrovsky    True  True  True
Turgenev     True  True  True
All          True  True  True


In [64]:
book_info2.equals(book_info)

True